import type { CaseSeverity } from "./case";
import type { IsoTimestamp } from "./primitives";

export const NOTIFICATION_CHANNELS = ["CONSOLE_EMAIL"] as const;
export type NotificationChannel = (typeof NOTIFICATION_CHANNELS)[number];

/** `ref` is an actor ID (never an address): addresses stay inside the channel adapter. */
export type NotificationRecipient = { readonly ref: string; readonly role?: string };

export type NotificationRequest = {
  readonly notificationId: string;
  readonly organizationId: string;
  readonly facilityId: string;
  readonly channel: NotificationChannel;
  readonly recipient: NotificationRecipient;
  readonly subject: string;
  readonly body: string;
  readonly caseId: string;
  readonly riskEventId: string;
  readonly severity: CaseSeverity;
  readonly requestedAt: IsoTimestamp;
};

/**
 * Outcome of one send attempt. SENT means the configured channel implementation accepted the
 * message (locally: ConsoleEmail); it is not proof that a person read it.
 */
export type NotificationResult = {
  readonly notificationId: string;
  readonly status: "SENT" | "FAILED";
  readonly channel: NotificationChannel;
  readonly recipientRef: string;
  readonly requestedAt: IsoTimestamp;
  readonly completedAt: IsoTimestamp;
  readonly failure?: { readonly code: string; readonly message: string };
};

export const ALERT_KINDS = ["INITIAL", "ESCALATION"] as const;
export type AlertKind = (typeof ALERT_KINDS)[number];

export const ALERT_STATUSES = ["REQUESTED", "SENT", "FAILED"] as const;
export type AlertStatus = (typeof ALERT_STATUSES)[number];

/**
 * An alert is a communication generated by a case (spec section 0), never the case itself.
 * Facts are deterministic: reason codes and a rule-based summary, no generated language.
 * Escalations are separate alerts, so the original alert and its delivery history survive.
 */
export type Alert = {
  readonly alertId: string;
  readonly organizationId: string;
  readonly facilityId: string;
  readonly caseId: string;
  readonly riskEventId: string;
  readonly kind: AlertKind;
  readonly severity: CaseSeverity;
  readonly hazardType: string;
  readonly reasonCodes: readonly string[];
  readonly summary: string;
  readonly recipient: NotificationRecipient;
  readonly channel: NotificationChannel;
  readonly status: AlertStatus;
  readonly attempts: readonly NotificationResult[];
  readonly maxAttempts: number;
  /** True once every allowed attempt has failed. */
  readonly exhausted: boolean;
  readonly nextRetryAt?: IsoTimestamp;
  readonly requestedAt: IsoTimestamp;
  readonly sentAt?: IsoTimestamp;
  readonly correlationId: string;
};

export const AUDIT_ACTIONS = [
  "CASE_CREATED",
  "DETECTION_RECORDED",
  "ALERT_REQUESTED",
  "ALERT_SENT",
  "ALERT_FAILED",
  "RISK_ALERTED",
  "RISK_ACKNOWLEDGED",
  "ACTION_ASSIGNED",
  "ACTION_ACKNOWLEDGED",
  "ACTION_REPORTED",
  "RISK_ESCALATED",
  "RISK_DISMISSED",
  "VERIFICATION_STARTED",
  "VERIFICATION_COMPLETED",
  "RECURRENCE_DETECTED",
  "CASE_REOPENED",
  "INTERVENTION_RECOMMENDED",
  "INTERVENTION_ACKNOWLEDGED",
  "INTERVENTION_RESOLVED",
  "EVIDENCE_PACKAGE_CREATED",
  "EVIDENCE_PACKAGE_READ",
  "SHARING_AGREEMENT_CREATED",
  "SHARING_AGREEMENT_REVOKED",
  "EVIDENCE_SHARED",
  "SHARING_STATE_CHANGED",
  "INSURER_EVIDENCE_READ",
  "INSURER_ACCESS_DENIED",
] as const;
export type AuditAction = (typeof AUDIT_ACTIONS)[number];

export type AuditDetails = Readonly<Record<string, string | number | boolean | readonly string[]>>;

/** Append-only operational audit record (hash chaining is later hardening). */
export type AuditEntry = {
  readonly auditId: string;
  readonly sequence: number;
  readonly organizationId: string;
  readonly facilityId: string;
  readonly caseId?: string;
  readonly actorId: string;
  readonly actorType: "USER" | "SYSTEM";
  readonly action: AuditAction;
  readonly targetType:
    | "CASE"
    | "RISK_EVENT"
    | "ACTION"
    | "ALERT"
    | "VERIFICATION"
    | "INTERVENTION"
    | "EVIDENCE_PACKAGE"
    | "SHARING_AGREEMENT";
  readonly targetId: string;
  readonly beforeState?: string;
  readonly afterState?: string;
  readonly correlationId: string;
  readonly at: IsoTimestamp;
  readonly details?: AuditDetails;
};
