import {
  EVIDENCE_BUILDER_VERSION,
  EVIDENCE_CANONICALIZATION,
  EVIDENCE_HASH_ALGORITHM,
  EVIDENCE_MANIFEST_SCHEMA,
  EVIDENCE_PACKAGE_SCHEMA,
  err,
  ok,
} from "@symbiosis/contracts";
import type {
  AuditEntry,
  Baseline,
  CanonicalObservation,
  DeviceFactSnapshot,
  EvidenceActionSummary,
  EvidenceArtifact,
  EvidenceArtifactDescriptor,
  EvidenceDataOrigin,
  EvidenceKind,
  EvidenceManifest,
  EvidencePackage,
  EvidencePayload,
  EvidenceSourceLabel,
  MitigationAction,
  Result,
  RiskEvent,
  RiskImprovementCase,
  VerificationAttempt,
} from "@symbiosis/contracts";
import { canonicalJson, toJsonValue } from "./canonical";
import { sha256OfCanonical } from "./hash";

export type EvidenceErrorCode =
  | "NOT_FOUND"
  | "FORBIDDEN"
  | "INVALID_REQUEST"
  | "VERIFICATION_NOT_COMPLETED"
  | "UNRESOLVED_EVIDENCE"
  | "INCONSISTENT_SOURCE"
  | "SERIALIZATION_FAILURE"
  | "STORAGE_FAILURE"
  | "INTEGRITY_FAILURE";

export type EvidenceError = {
  readonly code: EvidenceErrorCode;
  readonly message: string;
  readonly details?: readonly string[];
};

const fail = (code: EvidenceErrorCode, message: string, details?: readonly string[]) =>
  err<EvidenceError>({ code, message, ...(details !== undefined && { details }) });

export type ApprovedActionFact = {
  readonly actionLibraryId: string;
  readonly title: string;
  readonly libraryVersion: string;
};

/** A verification policy as used, so the package carries exactly what was applied. */
export type PolicyDocument = {
  readonly policyId: string;
  readonly policyVersion: string;
  readonly document: unknown;
};

/**
 * Everything the builder may use, already read from trusted stores by the caller. The builder
 * performs no I/O and has no access to anything else, so it cannot invent a fact: a value that is
 * not in this input cannot appear in the package.
 */
export type BuildEvidenceInput = {
  readonly packageId: string;
  /** The only time that enters the package, passed in explicitly (Clock). */
  readonly createdAt: string;
  readonly caseRecord: RiskImprovementCase;
  readonly event: RiskEvent;
  readonly attempt: VerificationAttempt;
  /** Earlier COMPLETED attempts of the same case, for recurrence/history context. */
  readonly priorAttempts: readonly VerificationAttempt[];
  readonly actions: readonly MitigationAction[];
  readonly observations: readonly CanonicalObservation[];
  readonly baselines: readonly Baseline[];
  /** The case audit trail (oldest first). */
  readonly auditEntries: readonly AuditEntry[];
  readonly policies: readonly PolicyDocument[];
  readonly approvedActions: readonly ApprovedActionFact[];
  /** Present only when a recommendation record exists for a RECOMMENDATION-origin case. */
  readonly recommendationSource?: EvidencePayload["recommendation"]["source"];
};

const REFERENCE_KINDS: readonly EvidenceKind[] = [
  "OBSERVATION",
  "BASELINE",
  "ACTION",
  "AUDIT",
  "POLICY",
  "DEVICE",
];

const compareDescriptors = (a: EvidenceArtifactDescriptor, b: EvidenceArtifactDescriptor) =>
  REFERENCE_KINDS.indexOf(a.kind) - REFERENCE_KINDS.indexOf(b.kind) ||
  (a.id < b.id ? -1 : a.id > b.id ? 1 : 0);

const SYNTHETIC_TEXT =
  "SYNTHETIC DATA: generated by the simulator. Not a real property or carrier observation.";

/** Derives the source label from the observations the package actually cites. */
export function sourceLabelFor(
  observations: readonly Pick<CanonicalObservation, "sourceType" | "sourceAdapter">[],
): EvidenceSourceLabel {
  const sourceTypes = [...new Set(observations.map((o) => o.sourceType as string))].sort();
  const sourceAdapters = [...new Set(observations.map((o) => o.sourceAdapter))].sort();
  let dataOrigin: EvidenceDataOrigin;
  let label: string;
  if (sourceTypes.length === 0) {
    dataOrigin = "NONE";
    label = "NO TELEMETRY REFERENCED: this package cites no observations.";
  } else if (sourceTypes.length === 1 && sourceTypes[0] === "SIMULATOR") {
    dataOrigin = "SYNTHETIC_SIMULATOR";
    label = SYNTHETIC_TEXT;
  } else if (sourceTypes.length === 1 && sourceTypes[0] === "HARDWARE") {
    dataOrigin = "PROTOTYPE_HARDWARE";
    label =
      "PROTOTYPE HARDWARE DATA: from a low-voltage bench model. Not an observation of a real insured property.";
  } else {
    dataOrigin = "MIXED";
    label = `MIXED DATA SOURCES (${sourceTypes.join(", ")}).${
      sourceTypes.includes("SIMULATOR") ? " Includes simulator-generated data." : ""
    } Not a real carrier observation unless every source is a real integration.`;
  }
  return {
    dataOrigin,
    synthetic: sourceTypes.includes("SIMULATOR"),
    sourceTypes,
    sourceAdapters,
    label,
  };
}

function snapshotFor(
  kind: EvidenceKind,
  id: string,
  input: BuildEvidenceInput,
): { found: true; record: unknown } | { found: false } {
  switch (kind) {
    case "OBSERVATION": {
      const o = input.observations.find((x) => x.observationId === id);
      return o === undefined ? { found: false } : { found: true, record: o };
    }
    case "BASELINE": {
      const b = input.baselines.find((x) => x.baselineId === id);
      return b === undefined ? { found: false } : { found: true, record: b };
    }
    case "ACTION": {
      const a = input.actions.find((x) => x.actionId === id);
      return a === undefined ? { found: false } : { found: true, record: a };
    }
    case "AUDIT": {
      const a = input.auditEntries.find((x) => x.auditId === id);
      return a === undefined ? { found: false } : { found: true, record: a };
    }
    case "POLICY": {
      const p = input.policies.find((x) => `POLICY:${x.policyId}:${x.policyVersion}` === id);
      return p === undefined
        ? { found: false }
        : {
            found: true,
            record: { policyId: p.policyId, policyVersion: p.policyVersion, document: p.document },
          };
    }
    case "DEVICE": {
      const deviceId = id.replace(/^DEVICE:/, "");
      const d: DeviceFactSnapshot | undefined = input.attempt.deviceSnapshots?.find(
        (x) => x.deviceId === deviceId,
      );
      return d === undefined ? { found: false } : { found: true, record: d };
    }
  }
}

/**
 * Builds an immutable evidence package from a COMPLETED verification and the trusted records it
 * references. Fails explicitly (never substitutes, skips or defaults) when a referenced record,
 * the device snapshot or the completion audit entry is missing, or when the sources disagree.
 * The package preserves the verification result as recorded: it never upgrades it, and a
 * package for NOT_IMPROVING, PARTIALLY_VERIFIED or INCONCLUSIVE says so.
 */
export function buildEvidencePackage(
  input: BuildEvidenceInput,
): Result<EvidencePackage, EvidenceError> {
  const { caseRecord: c, event, attempt } = input;
  const assessment = attempt.assessment;
  if (attempt.status !== "COMPLETED" || assessment === undefined) {
    return fail("VERIFICATION_NOT_COMPLETED", "An evidence package needs a completed verification");
  }
  const mismatches: string[] = [];
  if (attempt.caseId !== c.caseId) mismatches.push("verification belongs to another case");
  if (attempt.organizationId !== c.organizationId) mismatches.push("organization differs");
  if (attempt.facilityId !== c.facilityId) mismatches.push("facility differs");
  if (event.caseId !== c.caseId || event.eventId !== attempt.eventId) {
    mismatches.push("risk event does not belong to the verification");
  }
  if (assessment.verificationId !== attempt.verificationId) {
    mismatches.push("assessment belongs to another verification");
  }
  if (mismatches.length > 0) {
    return fail("INCONSISTENT_SOURCE", "Source records disagree", mismatches);
  }

  // Every typed reference must resolve to an existing record: nothing is skipped or invented.
  const references = attempt.evidenceReferences ?? [];
  const referenced = new Set(references.map((r) => r.id));
  const orphaned = assessment.evidenceIds.filter((id) => !referenced.has(id));
  if (orphaned.length > 0) {
    return fail(
      "UNRESOLVED_EVIDENCE",
      "The assessment cites evidence ids that have no typed reference",
      orphaned,
    );
  }
  const unresolved: string[] = [];
  const artifacts: EvidenceArtifact[] = [];
  try {
    for (const ref of references) {
      const found = snapshotFor(ref.kind, ref.id, input);
      if (!found.found) {
        unresolved.push(`${ref.kind}:${ref.id}`);
        continue;
      }
      const snapshot = toJsonValue(found.record);
      artifacts.push({ id: ref.id, kind: ref.kind, snapshot, sha256: sha256OfCanonical(snapshot) });
    }
  } catch (e) {
    return fail("SERIALIZATION_FAILURE", e instanceof Error ? e.message : String(e));
  }
  if (unresolved.length > 0) {
    return fail("UNRESOLVED_EVIDENCE", "Referenced evidence does not resolve", unresolved);
  }
  artifacts.sort(compareDescriptors);
  const descriptors: EvidenceArtifactDescriptor[] = artifacts.map((a) => ({
    id: a.id,
    kind: a.kind,
    sha256: a.sha256,
  }));

  // The completion audit entry bounds the audit references to what existed at verification time.
  const completion = input.auditEntries.find(
    (e) => e.action === "VERIFICATION_COMPLETED" && e.targetId === attempt.verificationId,
  );
  if (completion === undefined) {
    return fail("UNRESOLVED_EVIDENCE", "The verification completion audit entry is missing", [
      `AUDIT:VERIFICATION_COMPLETED:${attempt.verificationId}`,
    ]);
  }
  const trail = input.auditEntries.filter((e) => e.sequence <= completion.sequence);
  const ack = trail.find((e) => e.action === "RISK_ACKNOWLEDGED" && e.targetId === event.eventId);
  const reasonEntry = [...trail]
    .reverse()
    .find(
      (e) =>
        (e.action === "CASE_CREATED" ||
          e.action === "DETECTION_RECORDED" ||
          e.action === "RECURRENCE_DETECTED") &&
        Date.parse(e.at) >= Date.parse(event.detectedAt) &&
        Array.isArray(e.details?.reasonCodes),
    );

  const titleOf = (id: string) => input.approvedActions.find((a) => a.actionLibraryId === id);
  const reportedActions: EvidenceActionSummary[] = [];
  for (const actionId of attempt.actionIds) {
    const a = input.actions.find((x) => x.actionId === actionId);
    if (a === undefined) {
      return fail("UNRESOLVED_EVIDENCE", "A reported action of the verification is missing", [
        `ACTION:${actionId}`,
      ]);
    }
    const known = titleOf(a.actionLibraryId);
    reportedActions.push({
      actionId: a.actionId,
      actionLibraryId: a.actionLibraryId,
      ...(known !== undefined && { title: known.title }),
      ...((a.actionLibraryVersion ?? known?.libraryVersion) !== undefined && {
        libraryVersion: (a.actionLibraryVersion ?? known?.libraryVersion) as string,
      }),
      status: a.status,
      ...(a.assignedTo !== undefined && { assignedTo: a.assignedTo }),
      ...(a.assignedAt !== undefined && { assignedAt: a.assignedAt }),
      ...(a.acknowledgedAt !== undefined && { acknowledgedAt: a.acknowledgedAt }),
      ...(a.reportedBy !== undefined && { reportedBy: a.reportedBy }),
      ...(a.reportedAt !== undefined && { reportedAt: a.reportedAt }),
      ...(a.notes !== undefined && { notes: a.notes }),
      attachments: a.attachments ?? [],
    });
  }

  const observationArtifacts = input.observations.filter((o) =>
    references.some((r) => r.kind === "OBSERVATION" && r.id === o.observationId),
  );

  const origin = c.origin;
  const payload: EvidencePayload = {
    caseIdentity: {
      caseId: c.caseId,
      organizationId: c.organizationId,
      facilityId: c.facilityId,
      assetIds: [...c.assetIds],
      hazardType: c.hazardType,
      title: c.title,
      severity: c.severity,
      state: c.state,
      recurrenceCount: c.recurrenceCount,
      createdAt: c.createdAt,
    },
    recommendation: {
      origin,
      source:
        origin.type === "DETECTED_HAZARD"
          ? "SYMBIOSIS"
          : (input.recommendationSource ?? "UNSPECIFIED"),
      recommendationId: origin.type === "RECOMMENDATION" ? origin.recommendationId : null,
      approvedActions: input.approvedActions.map((a) => ({ ...a })),
    },
    riskEvent: {
      eventId: event.eventId,
      state: event.state,
      detectedAt: event.detectedAt,
      assetIds: [...event.assetIds],
      detectionReasonCodes:
        (reasonEntry?.details?.reasonCodes as readonly string[] | undefined) ?? [],
    },
    reportedActions,
    acknowledgement:
      ack === undefined
        ? null
        : { auditId: ack.auditId, acknowledgedBy: ack.actorId, acknowledgedAt: ack.at },
    baselineWindow: assessment.baselineWindow,
    postActionWindow: assessment.postActionWindow,
    requiredCriteria: assessment.requiredCriteria,
    supportingCriteria: assessment.supportingCriteria,
    quality: {
      dataCompleteness: assessment.dataCompleteness,
      telemetryConfidence: assessment.telemetryConfidence,
      deviceHealthStatus: assessment.deviceHealthStatus,
      authIntegrityStatus: assessment.authIntegrityStatus,
    },
    verification: {
      verificationId: attempt.verificationId,
      result: assessment.result,
      confidence: assessment.confidence,
      reasonCodes: assessment.reasonCodes ?? [],
      evaluatedAt: assessment.evaluatedAt,
      policyId: assessment.policyId,
      policyVersion: assessment.policyVersion,
    },
    recurrence: {
      recurrenceCount: c.recurrenceCount,
      recurrenceWatchEndsAt: attempt.recurrenceWatchEndsAt ?? null,
      priorVerificationIds: input.priorAttempts
        .filter((a) => a.status === "COMPLETED" && a.verificationId !== attempt.verificationId)
        .map((a) => a.verificationId),
    },
    versions: {
      verificationPolicy: { id: assessment.policyId, version: assessment.policyVersion },
      evidenceSchema: EVIDENCE_PACKAGE_SCHEMA,
      canonicalization: EVIDENCE_CANONICALIZATION,
      hashAlgorithm: EVIDENCE_HASH_ALGORITHM,
      builder: EVIDENCE_BUILDER_VERSION,
    },
    evidenceReferences: descriptors,
    auditReferences: trail.map((e) => ({
      auditId: e.auditId,
      action: e.action,
      at: e.at,
      actorId: e.actorId,
      actorType: e.actorType,
      targetType: e.targetType,
      targetId: e.targetId,
    })),
    source: sourceLabelFor(observationArtifacts),
  };

  try {
    const payloadSha256 = sha256OfCanonical(payload);
    const manifest: EvidenceManifest = {
      manifestSchema: EVIDENCE_MANIFEST_SCHEMA,
      hashAlgorithm: EVIDENCE_HASH_ALGORITHM,
      canonicalization: EVIDENCE_CANONICALIZATION,
      packageSchema: EVIDENCE_PACKAGE_SCHEMA,
      packageId: input.packageId,
      organizationId: c.organizationId,
      facilityId: c.facilityId,
      caseId: c.caseId,
      verificationId: attempt.verificationId,
      createdAt: input.createdAt,
      versions: payload.versions,
      payloadSha256,
      artifactCount: descriptors.length,
      artifacts: descriptors,
    };
    const pkg: EvidencePackage = {
      packageId: input.packageId,
      schemaVersion: EVIDENCE_PACKAGE_SCHEMA,
      organizationId: c.organizationId,
      facilityId: c.facilityId,
      caseId: c.caseId,
      verificationId: attempt.verificationId,
      createdAt: input.createdAt,
      payload,
      artifacts,
      manifest,
      manifestSha256: sha256OfCanonical(manifest),
    };
    canonicalJson(pkg); // proves the whole package is serializable before anything is stored
    return ok(pkg);
  } catch (e) {
    return fail("SERIALIZATION_FAILURE", e instanceof Error ? e.message : String(e));
  }
}
