import { chmodSync, existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { createBenchDeviceRecord } from "@symbiosis/adapter-esp32";
import {
  DeviceProvisioningError,
  Firestore,
  FirestoreDeviceRegistry,
  createProvisionSecrets,
  provisionDevice,
} from "@symbiosis/adapter-gcp";

/**
 * Operator-only provisioning of a PHYSICAL bench device (S10). Run from your own machine with
 * Application Default Credentials; never from a service or a browser.
 *
 *   GCP_PROJECT_ID=<id> pnpm provision:device \
 *     --confirm-project <id> --device-id DEV-PHX-BENCH-001 [--key-id KEY-PHX-001]
 *     [--org ORG-SIM-001] [--facility FAC-SIM-001]
 *     [--rotate-key]            new key id for an existing device (replay-recovery path)
 *     [--write-firmware-secrets] generate firmware/esp32-lab/include/secrets.h
 *     [--force-secrets-header]  overwrite an existing secrets.h
 *     [--dry-run]               validate arguments only; touches nothing
 *
 * Wi-Fi credentials for secrets.h come from SYM_WIFI_SSID / SYM_WIFI_PASSWORD (environment) and
 * are otherwise left as placeholders you edit by hand. The generated device key is written ONLY to
 * the git-ignored files below and is NEVER printed:
 *   .secrets/devices/<device>.<key>.json
 *   firmware/esp32-lab/include/secrets.h   (with --write-firmware-secrets)
 */
const argv = process.argv.slice(2);
const flag = (name: string) => argv.includes(`--${name}`);
const value = (name: string, fallback?: string): string | undefined => {
  const i = argv.indexOf(`--${name}`);
  return i >= 0 ? argv[i + 1] : fallback;
};

const project = process.env.GCP_PROJECT_ID ?? "";
const deviceId = value("device-id") ?? "";
const keyId = value("key-id") ?? deviceId.replace(/^DEV-/, "KEY-");
const organizationId = value("org", "ORG-SIM-001") as string;
const facilityId = value("facility", "FAC-SIM-001") as string;
const rotate = flag("rotate-key");

const record = createBenchDeviceRecord({ deviceId, keyId, organizationId, facilityId });
const apiBase = process.env.SYMBIOSIS_API_BASE_URL ?? "";

if (flag("dry-run")) {
  console.log(
    `dry run ok: would ${rotate ? "rotate the key of" : "register"} ${record.deviceId} ` +
      `(key id ${record.activeKeyId}) in ${organizationId}/${facilityId}. Nothing was changed.`,
  );
  process.exit(0);
}

if (project === "" || value("confirm-project") !== project) {
  throw new Error(
    "refusing to provision: pass --confirm-project <GCP_PROJECT_ID> matching GCP_PROJECT_ID",
  );
}

const db = new Firestore({ projectId: project });
const registry = new FirestoreDeviceRegistry({ db });

try {
  const result = await provisionDevice(
    {
      secrets: createProvisionSecrets(project),
      registry: {
        get: (id) => registry.get(id),
        create: (d) => registry.create(d),
        put: (d) => registry.put(d),
      },
    },
    {
      record,
      apiServiceAccount: `symbiosis-api@${project}.iam.gserviceaccount.com`,
      rotate,
    },
  );

  const dir = join(".secrets", "devices");
  mkdirSync(dir, { recursive: true });
  const keyFile = join(dir, `${result.deviceId}.${result.keyId}.json`);
  writeFileSync(
    keyFile,
    JSON.stringify(
      {
        deviceId: result.deviceId,
        keyId: result.keyId,
        deviceKeyHex: result.keyHex,
        secretManagerSecret: result.secretId,
        createdAt: new Date().toISOString(),
      },
      null,
      2,
    ),
    { mode: 0o600 },
  );
  try {
    chmodSync(keyFile, 0o600);
  } catch {
    // best effort on filesystems without POSIX modes (Windows)
  }

  const written = [`${keyFile} (device key; git-ignored)`];
  if (flag("write-firmware-secrets")) {
    const header = join("firmware", "esp32-lab", "include", "secrets.h");
    if (existsSync(header) && !flag("force-secrets-header")) {
      console.log(`secrets.h exists; not overwritten (use --force-secrets-header). ${header}`);
    } else {
      const q = (s: string) => JSON.stringify(s); // C string literal
      writeFileSync(
        header,
        [
          "#pragma once",
          "// GENERATED by `pnpm provision:device`. Git-ignored. Contains the device key: never commit.",
          `#define SYM_WIFI_SSID ${q(process.env.SYM_WIFI_SSID ?? "your-wifi-name")}`,
          `#define SYM_WIFI_PASSWORD ${q(process.env.SYM_WIFI_PASSWORD ?? "your-wifi-password")}`,
          `#define SYM_API_BASE_URL ${q(apiBase !== "" ? apiBase.replace(/\/$/, "") : "https://symbiosis-api-554089078085.us-central1.run.app")}`,
          `#define SYM_DEVICE_ID ${q(result.deviceId)}`,
          `#define SYM_KEY_ID ${q(result.keyId)}`,
          `#define SYM_DEVICE_KEY_HEX ${q(result.keyHex)}`,
          "",
        ].join("\n"),
        { mode: 0o600 },
      );
      written.push(`${header} (firmware secrets; git-ignored)`);
    }
  }

  // Deliberately no key in this output.
  console.log(
    `${result.rotated ? "rotated" : "provisioned"} ${result.deviceId} key ${result.keyId}\n` +
      `  secret: ${result.secretId}\n  written:\n    ${written.join("\n    ")}\n` +
      "  next: put Wi-Fi credentials in secrets.h, then flash the signing_test env first (H7).",
  );
} catch (e) {
  if (e instanceof DeviceProvisioningError) {
    console.error(`provisioning refused (${e.code}): ${e.message}`);
    process.exitCode = 1;
  } else {
    throw e;
  }
} finally {
  await db.terminate();
}
