"use client";

import { useState } from "react";
import {
  BASELINE_LABEL,
  DELIVERY_STATUS,
  KIND_LABELS,
  OUTCOME_LABELS,
  SCENARIO_ICONS,
  SENSOR_STATUS,
  WEATHER_STATUS,
  formatAge,
  formatClock,
  formatSensorValue,
  formatTemperature,
} from "../../lib/sim-format";
import type { Tone } from "../../lib/sim-format";
import { problemText, simPost } from "../../lib/sim-client";
import type { SimOverview, SimSensor, TimelineItem } from "../../lib/sim-types";
import { ControlForm } from "./ControlPanel";
import type { ControlSpec } from "./ControlPanel";

export function Pill({
  tone,
  icon,
  children,
  testId,
}: {
  readonly tone: Tone;
  readonly icon?: string;
  readonly children: React.ReactNode;
  readonly testId?: string;
}) {
  return (
    <span className={`badge tone-${tone}`} {...(testId !== undefined && { "data-testid": testId })}>
      {icon !== undefined && (
        <span className="badge-icon" aria-hidden="true">
          {icon}
        </span>
      )}
      <span>{children}</span>
    </span>
  );
}

// ---- weather ------------------------------------------------------------------------------------

export function WeatherCard({ overview }: { readonly overview: SimOverview }) {
  const w = overview.weather;
  const st = WEATHER_STATUS[w.status];
  return (
    <div className="card weather-card" data-testid="weather-card" data-weather-status={w.status}>
      <div className="card-head">
        <h3>Outdoor weather</h3>
        <Pill tone={st.tone} icon={st.icon} testId="weather-badge">
          {st.label}
        </Pill>
      </div>
      {w.reading !== undefined ? (
        <p className="weather-main">
          <strong data-testid="weather-temp">{formatTemperature(w.reading.temperatureC)}</strong>
          {w.reading.condition !== undefined && <span> · {w.reading.condition}</span>}
        </p>
      ) : (
        <p className="weather-main" data-testid="weather-temp">
          No reading
        </p>
      )}
      <dl className="facts">
        {w.reading?.relativeHumidityPct !== undefined && (
          <>
            <dt>Humidity</dt>
            <dd>{w.reading.relativeHumidityPct}%</dd>
          </>
        )}
        {w.reading?.windSpeedKph !== undefined && (
          <>
            <dt>Wind</dt>
            <dd>{w.reading.windSpeedKph} km/h</dd>
          </>
        )}
        {w.reading !== undefined && (
          <>
            <dt>Provider time</dt>
            <dd>
              {formatClock(w.reading.observedAt)} ({formatAge(w.ageSeconds)})
            </dd>
          </>
        )}
        <dt>Source</dt>
        <dd>
          {w.status === "LIVE" || (w.status === "STALE" && w.live)
            ? "Google Maps Platform Weather API"
            : w.status === "SIMULATED"
              ? "Set by the evaluator (simulation)"
              : "None"}
        </dd>
        {w.mode === "LIVE" && (
          <>
            <dt>Provider calls today</dt>
            <dd>
              {w.callsToday} of {w.maxCallsPerDay}
            </dd>
          </>
        )}
      </dl>
      {(w.status === "UNAVAILABLE" || w.status === "NOT_CONFIGURED") && (
        <p className="notice notice-error" role="status">
          <strong>WEATHER UNAVAILABLE / INSUFFICIENT CONTEXT.</strong> No weather is invented. The
          rule can still use a rising zone temperature as its context.
        </p>
      )}
      {w.status === "STALE" && (
        <p className="notice notice-warn" role="status">
          The last provider reading is old. It keeps its own timestamp and is judged by that.
        </p>
      )}
      <p className="muted">
        Live weather is a trusted data provider reading. It is not generated by an AI model and it
        is never shown as an AI explanation.
      </p>
    </div>
  );
}

// ---- sensor detail ----------------------------------------------------------------------------------

const SENSOR_SPECS: Readonly<Record<string, readonly ControlSpec[]>> = {
  "SNS-ZONE-TEMP": [
    { kind: "number", field: "zoneTemperatureC" },
    { kind: "sensor", group: "hvac" },
  ],
  "SNS-ZONE-RH": [
    { kind: "number", field: "relativeHumidityPct" },
    { kind: "sensor", group: "hvac" },
  ],
  "SNS-CUA-VIB": [
    { kind: "number", field: "vibrationRmsMs2" },
    { kind: "sensor", group: "vibration" },
  ],
  "SNS-CUA-CURRENT": [
    { kind: "number", field: "currentA" },
    { kind: "sensor", group: "meter" },
  ],
  "SNS-CUA-LOAD": [
    { kind: "number", field: "loadPercent" },
    { kind: "sensor", group: "meter" },
  ],
  "SNS-CUA-RUN": [
    { kind: "toggle", field: "primaryRunning", label: "Primary cooling unit (CU-A) running" },
    { kind: "sensor", group: "meter" },
  ],
  "SNS-CUB-RUN": [
    { kind: "toggle", field: "backupRunning", label: "Backup cooling unit (CU-B) running" },
    { kind: "sensor", group: "hvac" },
  ],
  "SNS-OUTDOOR-TEMP": [
    { kind: "number", field: "outdoorTemperatureC", hint: "Only used in Simulated weather mode." },
  ],
};

export function SensorDetail({
  overview,
  sensor,
  onApplied,
}: {
  readonly overview: SimOverview;
  readonly sensor: SimSensor | undefined;
  readonly onApplied: () => void;
}) {
  if (sensor === undefined) {
    return (
      <div className="card" data-testid="sensor-detail-empty">
        <h3>Sensor details</h3>
        <p className="muted">
          Select a sensor on the diagram to see its reading, its trust and where it comes from.
        </p>
      </div>
    );
  }
  const st = SENSOR_STATUS[sensor.status];
  const device = overview.devices.find((d) => d.deviceId === sensor.deviceId);
  const specs = SENSOR_SPECS[sensor.sensorId] ?? [];
  return (
    <div className="card" data-testid="sensor-detail" data-sensor-id={sensor.sensorId}>
      <div className="card-head">
        <h3>{sensor.name}</h3>
        <Pill tone={st.tone} icon={st.icon} testId="sensor-status">
          {st.label}
        </Pill>
      </div>
      <p className="sensor-value" data-testid="sensor-value">
        {formatSensorValue(sensor)}
      </p>
      <dl className="facts">
        <dt>Equipment or zone</dt>
        <dd>{sensor.assetName}</dd>
        <dt>Last update</dt>
        <dd>
          {sensor.observedAt === null
            ? "no data"
            : `${formatClock(sensor.observedAt)} (${formatAge(sensor.ageSeconds)})`}
        </dd>
        <dt>Quality / trust</dt>
        <dd>
          {sensor.trusted === null
            ? "not available"
            : sensor.trusted
              ? `Trusted (confidence ${sensor.confidence})`
              : `Not trusted: ${sensor.trustNote ?? ""}`}
        </dd>
        <dt>Source</dt>
        <dd>
          {sensor.sourceLabel ?? "none"}
          {sensor.synthetic === true && (
            <>
              {" "}
              ·{" "}
              <Pill tone="synthetic" icon="◇">
                Simulation data
              </Pill>
            </>
          )}
        </dd>
        <dt>Adapter</dt>
        <dd>
          <code>{sensor.sourceAdapter ?? "none"}</code>
        </dd>
        {device !== undefined && (
          <>
            <dt>Gateway health</dt>
            <dd>
              {device.health} (last seen{" "}
              {device.lastSeenAt === null ? "never" : formatClock(device.lastSeenAt)})
            </dd>
          </>
        )}
      </dl>
      <ControlForm
        overview={overview}
        specs={specs}
        title="Change this reading in the simulated world"
        idPrefix="sensor"
        disabled={!overview.permissions.control}
        onApplied={onApplied}
      />
    </div>
  );
}

// ---- scenarios -------------------------------------------------------------------------------------------

export function ScenarioBar({
  overview,
  onApplied,
}: {
  readonly overview: SimOverview;
  readonly onApplied: () => void;
}) {
  const [busy, setBusy] = useState<string | null>(null);
  const [message, setMessage] = useState<{ kind: "ok" | "error"; text: string } | null>(null);
  const allowed = overview.permissions.control;
  async function apply(id: string) {
    setBusy(id);
    setMessage(null);
    const r = await simPost<unknown>("simulation/scenario", {
      scenarioId: id,
      expectedRevision: overview.session.revision,
    });
    setBusy(null);
    if (r.ok) {
      setMessage({ kind: "ok", text: "Scenario applied to the simulated world." });
      onApplied();
    } else {
      setMessage({ kind: "error", text: problemText(r.problem) });
      if (r.problem.code === "REVISION_CONFLICT") onApplied();
    }
  }
  return (
    <div>
      <p className="muted">
        A scenario changes only the simulated physical world. It never creates a case, sets a
        severity or decides a verification result: the platform's deterministic rules decide that
        from what the sensors then report.
      </p>
      <div className="scenario-grid" role="group" aria-label="Scenario library">
        {overview.scenarios.map((s) => {
          const current = overview.session.scenarioId === s.id;
          return (
            <button
              key={s.id}
              type="button"
              className={`scenario${current ? " scenario-current" : ""}`}
              data-testid={`scenario-${s.id}`}
              aria-pressed={current}
              disabled={!allowed || busy !== null}
              onClick={() => void apply(s.id)}
              title={s.expectation}
            >
              <span className="scenario-icon" aria-hidden="true">
                {SCENARIO_ICONS[s.id] ?? "•"}
              </span>
              <span className="scenario-body">
                <strong>{s.label}</strong>
                <span>{s.summary}</span>
                {s.rampSeconds > 0 && (
                  <span className="muted">Develops over {s.rampSeconds} s</span>
                )}
              </span>
            </button>
          );
        })}
      </div>
      {message !== null && (
        <p
          className={message.kind === "ok" ? "notice notice-ok" : "notice notice-error"}
          role={message.kind === "ok" ? "status" : "alert"}
          data-testid="scenario-message"
        >
          {message.text}
        </p>
      )}
    </div>
  );
}

// ---- the rule's own conclusion ------------------------------------------------------------------------------

const fmt = (n: number | null, unit: string) =>
  n === null ? "—" : `${n}${unit === "%" ? "%" : ""}`;

export function RulePanel({ overview }: { readonly overview: SimOverview }) {
  const r = overview.rule;
  const outcome = r.outcome === null ? undefined : OUTCOME_LABELS[r.outcome];
  const required = r.persistence?.required ?? 0;
  const done = r.persistence?.qualifyingEvaluations ?? 0;
  return (
    <div data-testid="rule-panel">
      <div className="rule-head">
        <Pill tone="synthetic" icon="◇">
          {overview.policy.label} {overview.policy.activeLabel}
        </Pill>
        {outcome !== undefined ? (
          <Pill tone={outcome.tone} icon={outcome.icon} testId="rule-outcome">
            {outcome.label}
          </Pill>
        ) : (
          <Pill tone="info" icon="◔" testId="rule-outcome">
            Waiting for the first evaluation
          </Pill>
        )}
        <span className="muted">
          Rule {r.ruleId ?? "—"} version {r.ruleVersion ?? "—"}
          {r.evaluatedAt !== null && <> · evaluated {formatClock(r.evaluatedAt)}</>}
        </span>
      </div>
      <div className="table-wrap">
        <table className="table rule-table">
          <caption className="visually-hidden">What the deterministic rule saw</caption>
          <thead>
            <tr>
              <th scope="col">Condition</th>
              <th scope="col">Current</th>
              <th scope="col">Threshold</th>
              <th scope="col">Met?</th>
              <th scope="col">Source</th>
            </tr>
          </thead>
          <tbody>
            {r.conditions.map((c) => (
              <tr key={c.id} data-testid={`rule-${c.id}`} data-met={String(c.met)}>
                <th scope="row">
                  {c.label}
                  <span className="muted block">{c.role}</span>
                </th>
                <td>
                  {fmt(c.value, c.unit)}{" "}
                  <span className="muted">{c.unit === "%" ? "" : c.unit}</span>
                </td>
                <td>
                  {c.operator} {c.threshold ?? "—"}{" "}
                  <span className="muted">{c.unit === "%" ? "%" : c.unit}</span>
                </td>
                <td>
                  {c.met === null ? (
                    <Pill tone="neutral" icon="–">
                      Unknown
                    </Pill>
                  ) : c.met ? (
                    <Pill tone="danger" icon="✓">
                      Met
                    </Pill>
                  ) : (
                    <Pill tone="good" icon="✗">
                      Not met
                    </Pill>
                  )}
                </td>
                <td>
                  <span className={c.source.includes("SIMULATED") ? "tag tag-sim" : "tag"}>
                    {c.source}
                  </span>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      <p className="rule-compound">
        <strong>Compound rule:</strong> vibration abnormal AND current abnormal AND (heat context OR
        a rising zone temperature), persisting for {required || "several"} checks in a row. The
        backend rule decides; this table shows what it recorded.
      </p>
      <div
        className="persistence"
        data-testid="persistence"
        aria-label={`Persistence ${done} of ${required}`}
      >
        <span>Persistence</span>
        <div className="persistence-steps" aria-hidden="true">
          {Array.from({ length: Math.max(required, 1) }, (_, i) => (
            <span key={i} className={i < done ? "persistence-step on" : "persistence-step"} />
          ))}
        </div>
        <strong data-testid="persistence-text">
          {done} / {required || "—"}
        </strong>
      </div>
      <div className="baseline-row" aria-label="Baseline learning">
        <span>Baselines:</span>
        {overview.baseline.signals.map((b) => (
          <Pill
            key={b.signal}
            tone={b.status === "READY" ? "good" : "info"}
            icon={b.status === "READY" ? "✓" : "◔"}
            testId={`baseline-${b.signal}`}
          >
            {b.label}: {BASELINE_LABEL[b.status] ?? b.status}
          </Pill>
        ))}
      </div>
      {!overview.baseline.ready && (
        <p className="notice notice-warn" role="status" data-testid="baseline-learning">
          The system is learning what normal looks like. Keep the world normal until every baseline
          is Ready. Abnormal scenarios are held back until then, because a baseline learns whatever
          it sees.
        </p>
      )}
      <div className="history-strip" role="img" aria-label="Recent sample checks, oldest to newest">
        {r.history.map((h) => {
          const o = OUTCOME_LABELS[h.outcome];
          return (
            <span
              key={h.at}
              className={`history-cell tone-${o?.tone ?? "neutral"}`}
              title={`${formatClock(h.at)}: ${o?.label ?? h.outcome}${h.qualifying > 0 ? ` (persistence ${h.qualifying}/${h.required})` : ""}`}
            />
          );
        })}
      </div>
    </div>
  );
}

// ---- notifications --------------------------------------------------------------------------------------------------

export function NotificationsPanel({
  overview,
  onChecked,
}: {
  readonly overview: SimOverview;
  readonly onChecked: () => void;
}) {
  const [msg, setMsg] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  async function runChecks() {
    setBusy(true);
    setMsg(null);
    const r = await simPost<unknown>("simulation/tick", {});
    setBusy(false);
    setMsg(r.ok ? "The scheduler checks ran." : problemText(r.problem));
    if (r.ok) onChecked();
  }
  return (
    <div data-testid="notifications-panel">
      <p className="muted">
        Each row is a persisted delivery attempt. An attempt is created before sending, so a
        duplicate event can never send twice. Follow-ups are decided by a versioned policy from
        verification results, never by an AI.
      </p>
      {overview.notifications.length === 0 ? (
        <p className="empty-line" data-testid="notifications-empty">
          No notifications yet. They appear when a case opens.
        </p>
      ) : (
        <div className="table-wrap">
          <table className="table">
            <caption className="visually-hidden">Notification deliveries</caption>
            <thead>
              <tr>
                <th scope="col">Kind</th>
                <th scope="col">To</th>
                <th scope="col">Channel</th>
                <th scope="col">Status</th>
                <th scope="col">Time</th>
              </tr>
            </thead>
            <tbody>
              {overview.notifications.map((d) => {
                const s = DELIVERY_STATUS[d.status];
                return (
                  <tr
                    key={d.deliveryId}
                    data-testid="delivery-row"
                    data-kind={d.kind}
                    data-status={d.status}
                  >
                    <th scope="row">
                      {KIND_LABELS[d.kind] ?? d.kind}
                      <span className="muted block">{d.subject}</span>
                    </th>
                    <td>
                      {d.recipientRole ?? d.recipientRef}
                      {d.addressHint !== null && (
                        <span className="muted block">{d.addressHint}</span>
                      )}
                    </td>
                    <td>{d.channel === "EMAIL" ? "Email" : "Console (no email sent)"}</td>
                    <td>
                      <Pill tone={s?.tone ?? "neutral"} icon={s?.icon ?? "•"}>
                        {s?.label ?? d.status} · attempt {d.attempt}
                      </Pill>
                      {d.failure !== null && (
                        <span className="muted block">
                          {d.failure.code}
                          {d.failure.retryable ? " (will retry)" : " (permanent)"}
                        </span>
                      )}
                    </td>
                    <td>{formatClock(d.completedAt ?? d.requestedAt)}</td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      )}
      <div className="control-actions">
        <button
          type="button"
          className="btn btn-small"
          data-testid="run-checks"
          disabled={busy || !overview.permissions.control}
          onClick={() => void runChecks()}
        >
          {busy ? "Running…" : "Run scheduler checks now"}
        </button>
        <span className="muted">
          Verification starts and completes on these checks (also run every minute).
        </span>
      </div>
      {msg !== null && (
        <p className="notice notice-ok" role="status">
          {msg}
        </p>
      )}
    </div>
  );
}

// ---- timeline --------------------------------------------------------------------------------------------------------

const TONE_ICON: Readonly<Record<string, string>> = { info: "•", good: "✓", warn: "▲", bad: "✕" };
const TONE_CLASS: Readonly<Record<string, string>> = {
  info: "info",
  good: "good",
  warn: "warn",
  bad: "danger",
};

export function TimelinePanel({ items }: { readonly items: readonly TimelineItem[] }) {
  if (items.length === 0) {
    return (
      <p className="empty-line" data-testid="timeline-empty">
        Nothing has happened yet. Start the simulation.
      </p>
    );
  }
  return (
    <ol
      className="sim-timeline"
      data-testid="sim-timeline"
      aria-label="Live event timeline, oldest first"
    >
      {items.map((i, n) => (
        <li
          key={`${i.at}-${n}`}
          className={`sim-tl-item tone-${TONE_CLASS[i.tone] ?? "info"}`}
          data-kind={i.kind}
        >
          <time dateTime={i.at}>{formatClock(i.at)}</time>
          <span className="sim-tl-icon" aria-hidden="true">
            {TONE_ICON[i.tone] ?? "•"}
          </span>
          <span className="sim-tl-text">
            <strong>{i.title}</strong>
            {i.detail !== undefined && i.detail !== "" && (
              <span className="muted block">{i.detail}</span>
            )}
          </span>
        </li>
      ))}
    </ol>
  );
}
